version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bk_globalshot_db
    environment:
      POSTGRES_USER: globalshotuser
      POSTGRES_PASSWORD: globalshotsecret
      POSTGRES_DB: globalshotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
